export type Language = "en" | "my";

export const strings = {
  en: {
    appName: "Senior Computer LMS",
    appSubtitle: "Offline computer and AI lessons",
    modules: "Modules",
    search: "Search",
    bookmarks: "Bookmarks",
    flashcards: "Flashcards",
    downloads: "Downloads",
    settings: "Settings",
    biggerText: "Bigger text",
    smallerText: "Smaller text",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    highContrast: "High contrast",
    startLearning: "Start Learning",
    continue: "Continue Where I Left Off",
    progress: "Your learning progress",
    lessonsComplete: "lessons complete",
    next: "Next",
    allModules: "All Modules",
    openLesson: "Open lesson",
    viewLessons: "View lessons",
    completed: "Completed",
    backToModules: "Back to modules",
    markComplete: "Mark complete",
    lessonComplete: "Lesson complete",
    bookmarkLesson: "Bookmark lesson",
    removeBookmark: "Remove bookmark",
    previousLesson: "Previous lesson",
    nextLesson: "Next lesson",
    practiceFlashcards: "Practice flashcards",
    lessonSections: "Lesson sections",
    noBookmarks: "No bookmarks yet.",
    download: "Download",
    increaseTextSize: "Increase text size",
    decreaseTextSize: "Decrease text size",
    highContrastMode: "High contrast mode",
    simpleMode: "Simple mode",
    focusMode: "Read focus mode",
    resetProgress: "Reset progress",
    language: "Language",
    english: "English",
    burmese: "Burmese"
  },
  my: {
    appName: "Senior Computer LMS",
    appSubtitle: "Offline Computer နှင့် AI သင်ခန်းစာများ",
    modules: "Modules",
    search: "ရှာရန်",
    bookmarks: "Bookmarks",
    flashcards: "Flashcards",
    downloads: "Downloads",
    settings: "Settings",
    biggerText: "စာလုံးကြီးမယ်",
    smallerText: "စာလုံးသေးမယ်",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    highContrast: "High contrast",
    startLearning: "စလေ့လာမယ်",
    continue: "နောက်ဆုံးနေရာက ဆက်မယ်",
    progress: "သင်ယူမှု Progress",
    lessonsComplete: "lessons ပြီးပါပြီ",
    next: "နောက်တစ်ခု",
    allModules: "Modules အားလုံး",
    openLesson: "Lesson ဖွင့်မယ်",
    viewLessons: "Lessons ကြည့်မယ်",
    completed: "ပြီးပါပြီ",
    backToModules: "Modules သို့ ပြန်မယ်",
    markComplete: "ပြီးပြီဟု မှတ်မယ်",
    lessonComplete: "Lesson ပြီးပါပြီ",
    bookmarkLesson: "Bookmark လုပ်မယ်",
    removeBookmark: "Bookmark ဖြုတ်မယ်",
    previousLesson: "အရင် Lesson",
    nextLesson: "နောက် Lesson",
    practiceFlashcards: "Flashcards လေ့ကျင့်မယ်",
    lessonSections: "Lesson အပိုင်းများ",
    noBookmarks: "Bookmark မရှိသေးပါ။",
    download: "Download",
    increaseTextSize: "စာလုံးကြီးမယ်",
    decreaseTextSize: "စာလုံးသေးမယ်",
    highContrastMode: "High contrast mode",
    simpleMode: "Simple mode",
    focusMode: "Read focus mode",
    resetProgress: "Progress reset လုပ်မယ်",
    language: "ဘာသာစကား",
    english: "English",
    burmese: "မြန်မာ"
  }
} satisfies Record<Language, Record<string, string>>;

export function t(language: Language) {
  return strings[language] ?? strings.en;
}
